# Generated by Django 3.2 on 2024-10-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=15)),
                ('Nombre', models.CharField(max_length=20)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Stock', models.IntegerField()),
                ('Precio', models.IntegerField()),
            ],
        ),
    ]
